EmployeeDemo/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <label>Employee</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Employee Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Employees</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

EmployeeDemo/force-app/main/default/objects/Employee__c/fields/Age__c.field-meta.xml
<CustomField>
    <fullName>Age__c</fullName>
    <formula>ABS( DateOfBirth__c -  TODAY() )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Age</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

EmployeeDemo/force-app/main/default/objects/Employee__c/fields/Certifications__c.field-meta.xml
<CustomField>
    <fullName>Certifications__c</fullName>
    <label>Certifications</label>
    <type>TextArea</type>
</CustomField>

EmployeeDemo/force-app/main/default/objects/Employee__c/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>FirstName</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

EmployeeDemo/force-app/main/default/objects/Employee__c/fields/FullName__c.field-meta.xml
<CustomField>
    <fullName>FullName__c</fullName>
    <formula>FirstName__c  &amp;  LastName__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>FullName</label>
    <type>Text</type>
</CustomField>

EmployeeDemo/force-app/main/default/objects/Employee__c/fields/Position__c.field-meta.xml
<CustomField>
    <fullName>Position__c</fullName>
    <label>Position</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Member</fullName>
            </value>
            <value>
                <fullName>Leader</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

EmployeeDemo/force-app/main/default/classes/EmployeeController.cls
public with sharing class EmployeeController {
    public EmployeeController() {

    }

    // get list employee
    @AuraEnabled(cacheable=true)
    public static List<Employee__c> getAllEmployees(){
        return [
            SELECT 
            Age__c,
            Certifications__c,
            DateOfBirth__c,
            Email__c,
            Experience__c,
            FirstName__c,
            FullName__c,
            LastName__c,
            PhoneNumber__c,
            Position__c
            FROM Employee__c
            LIMIT 10
        ];
    }
}